apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: radioshash-network-policy
spec:
  podSelector:
    matchLabels:
      name: radioshash
      app: radioshash-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.0.0.0/16
    ports:
    - protocol: TCP
      port: 5000
