apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: radioshash-network-policy
spec:
  podSelector:
    matchLabels:
      name: radioshash
      app: radioshash-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
      #dig +short worker-lb-1565124959.us-east-1.elb.amazonaws.com : this command to resolve lb dns 
        cidr:
          - 44.215.190.219
          - 54.147.51.238
    ports:
    - protocol: TCP
      port: 5000
